### ISSUE TITLE
HowTo color text instead of highlighting the whole line

### ISSUE THREAD

**Issue by andreabenini** [FlashSystems/LogView#2]
Hi and thank you for this wonderful plugin.
I just like to ask a question abount its customization, is there a way to color the text instead of applying a colored border to the entire line ?
It could be a nice thing because when you have a different color in each single line it might be more unreadable when compared to a colored text. Is there a way to do it ?

Thanks
Ben

**Comment by FlashSystems** [comment]
I don't think Sublime Text can do this. Coloring the text (or the background) can (afaik) only be done by a syntax highlighter. As soon as time permits I'll look into this suggestion. If it's possible without using a syntax highlighter (because this would make the configurable keywords impossible) I'll implement a config option for this.

**Comment by abdulloh-abid** [comment]
hi, is there any update on highlighting the error messages with different font colour, please?

this plugin is excellent, however it can be improved by adding extra functionality mentioned above

**Comment by FlashSystems** [comment]
I've just released a new version of this plugin that enhances the configuration options for the line highlighting. Maybe one of the new coloring styles suites your needs.
Coloring the text is still not possible, though. This is the domain of the syntax highlighter and I don't want to interfere with that. If you want colored text, you need to build a new syntax file that colors the lines you want.
